GET http://localhost:3000


# ---------------- Events

###
GET http://localhost:3000/events


###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "description": "This is a new event",
    "date": "2017-01-01T00:00:00",
    "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}


###
GET http://localhost:3000/events/{{eventId}}


###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "Updated Event",
    //"description": "This is a new event",
    "date": "2017-01-01T00:00:00",
    "price": 500
}


###
DELETE http://localhost:3000/events/{{eventId}}



# ---------------------- Spots

###
GET http://localhost:3000/events/{{eventId}}/spots


###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "New Spot"
}

###
@spotId = {{ createSpot.response.body.id }}


###
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}


###
PATCH http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
    "name": "Updated Spot"
}


###
DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
